services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: persistance
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

  adminer:
    image: adminer
    container_name: adminer-container
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    restart: always

  symfony:
    build: .
    container_name: symfony-container
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:persistance@mysql:3306/persistance

volumes:
  mysql-data:
